#!/usr/bin/python

import i3
import re

def now_playing():
    for ws_num in range(1,11):
        workspace = i3.filter(num=ws_num)
        if not workspace:
            continue
        workspace = workspace[0]
        windows = i3.filter(workspace, nodes=[])
        instances = {}
        # Adds windows and their ids to the clients dictionary
        for window in windows:
            if window['name'].endswith(" - Google Play Music"):
		name = re.sub(" - Google Play Music$", '', window['name'])
		if ' - ' in name:
		    return name
    return ""

print now_playing()
print ''
